<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-26T20:50:39 IST" name="Default suite" finished-at="2023-05-26T20:50:58 IST" duration-ms="18736">
    <groups>
    </groups>
    <test started-at="2023-05-26T20:50:39 IST" name="Default test" finished-at="2023-05-26T20:50:58 IST" duration-ms="18736">
      <class name="Runner_Scripts.TestScript1">
        <test-method is-config="true" signature="openApp()[pri:0, instance:Runner_Scripts.TestScript1@33990a0c]" started-at="2023-05-26T20:50:39 IST" name="openApp" finished-at="2023-05-26T20:50:43 IST" duration-ms="4252" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="test1(java.lang.String,java.lang.String)[pri:0, instance:Runner_Scripts.TestScript1@33990a0c]" started-at="2023-05-26T20:50:43 IST" name="test1" data-provider="testdata" finished-at="2023-05-26T20:50:47 IST" duration-ms="3530" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Santhosh]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[1234]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at Runner_Scripts.TestScript1.test1(TestScript1.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test1 -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:Runner_Scripts.TestScript1@33990a0c]" started-at="2023-05-26T20:50:47 IST" name="closeApp" finished-at="2023-05-26T20:50:49 IST" duration-ms="2385" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test1 status=FAILURE method=TestScript1.test1(java.lang.String,java.lang.String)[pri:0, instance:Runner_Scripts.TestScript1@33990a0c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
        <test-method is-config="true" signature="openApp()[pri:0, instance:Runner_Scripts.TestScript1@33990a0c]" started-at="2023-05-26T20:50:49 IST" name="openApp" finished-at="2023-05-26T20:50:52 IST" duration-ms="3404" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- openApp -->
        <test-method signature="test2()[pri:0, instance:Runner_Scripts.TestScript1@33990a0c]" started-at="2023-05-26T20:50:52 IST" name="test2" finished-at="2023-05-26T20:50:57 IST" duration-ms="4593" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test2 -->
        <test-method is-config="true" signature="closeApp(org.testng.ITestResult)[pri:0, instance:Runner_Scripts.TestScript1@33990a0c]" started-at="2023-05-26T20:50:57 IST" name="closeApp" finished-at="2023-05-26T20:50:58 IST" duration-ms="505" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test2 status=SUCCESS method=TestScript1.test2()[pri:0, instance:Runner_Scripts.TestScript1@33990a0c] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- Runner_Scripts.TestScript1 -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
